#!/bin/sh

DEPLOY_DIR=deploy/bosque
BASEDIR=$(dirname "$0")
SOURCE=bosque
DEPLOYQT="linuxdeployqt"

if [ ! -e $SOURCE ]; then
  echo "Compiled executable not exists [$SOURCE]"
  exit 1
fi

rm -rf deploy
mkdir -p $DEPLOY_DIR

echo "Copying executable binary [$SOURCE] to [$DEPLOY_DIR]"
cp -Rf $SOURCE $DEPLOY_DIR

echo "Retrieving Qt dependencies"
$DEPLOYQT $DEPLOY_DIR/$SOURCE
if [ $? -ne 0 ]; then
  echo "Error at deploying dependencies"
  rm -prf $DEPLOY_DIR
  exit $?
fi

if [ -e $BASEDIR/../addbin ]; then
  echo "Adding external applications"
  $BASEDIR/../addbin linux $DEPLOY_DIR
fi

exit 0







