#!/bin/sh

BASEDIR=$(dirname "$0")
SOURCE=bosque
VERSION=$(cat $BASEDIR/../data/version | tr . _ | tr -d \")

if [ ! -d $SOURCE ]; then
  echo "Deploy directory not exists";
  exit 1;
fi

tar zcvf bosque_$VERSION\_linux.tar.gz $SOURCE








