#!/bin/sh

BASEDIR=$(dirname "$0")
SOURCE=bosque/bosque.dmg
VERSION=$(cat $BASEDIR/../data/version | tr . _ | tr -d \")

if [ ! -e $SOURCE ]; then
  echo "Deploy dmg not exists";
  exit 1;
fi

cp -f $SOURCE bosque_$VERSION\_osx.dmg
