#!/bin/sh

APP=bosque
OS=osx

./files/$OS/compile

if [ $? -ne 0 ]; then
  echo "Error at compiling";
  exit 1;
fi

if [ ! -d app ]; then
  echo "Application not generated";
  exit 1;
fi

cd app
./../files/$OS/deploy

cd deploy
./../../files/$OS/package

scp $APP_*_*.* imo-deploy:/server/sites/imo-inf/downloads/$APP/








